force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <description>An MLB game.</description>
    <label>Game</label>
    <nameField>
        <displayFormat>MLB-{00000}</displayFormat>
        <label>Game Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/fields/Game_Sports_Data_ID__c.field-meta.xml
<CustomField>
    <fullName>Game_Sports_Data_ID__c</fullName>
    <externalId>true</externalId>
    <label>Game Sports Data ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Inning__c/Inning__c.object-meta.xml
<CustomObject>
    <description>An MLB game inning.</description>
    <label>Inning</label>
    <nameField>
        <displayFormat>INN-{000000}</displayFormat>
        <label>Inning Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Innings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inning__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <label>Game</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Innings</relationshipLabel>
    <relationshipName>Innings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>An MLB team.</description>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Abbreviation__c.field-meta.xml
<CustomField>
    <fullName>Abbreviation__c</fullName>
    <externalId>true</externalId>
    <label>Abbreviation</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/assignGamestoInnings.cls
global class assignGamestoInnings{
   @InvocableMethod
   public static List<List<Inning__c>> run(List<List<Inning__c>> inputInnings) {
       
      List<Team__c> allTeams = [SELECT Id,Abbreviation__c FROM Team__c LIMIT 100];
      Game__c game = [SELECT Id,Game_Sports_Data_ID__c FROM Game__c WHERE Game_Sports_Data_ID__c = :integer.valueof(inputInnings[0][0].Game__c)];
      
      for (List<Inning__c> inningList : inputInnings) {
          for (Inning__c inning : inningList) {
              inning.Game__c = game.Id;
          }
     }
      return inputInnings;
   }
}