force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <description>An MLB game.</description>
    <label>Game</label>
    <nameField>
        <displayFormat>MLB-{00000}</displayFormat>
        <label>Game Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/fields/Stadium__c.field-meta.xml
<CustomField>
    <fullName>Stadium__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stadium</label>
    <referenceTo>Stadium__c</referenceTo>
    <relationshipLabel>Games</relationshipLabel>
    <relationshipName>Games</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stadium__c/Stadium__c.object-meta.xml
<CustomObject>
    <description>An MLB stadium.</description>
    <label>Stadium</label>
    <nameField>
        <label>Stadium Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stadiums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stadium__c/fields/Stadium_Sports_Data_ID__c.field-meta.xml
<CustomField>
    <fullName>Stadium_Sports_Data_ID__c</fullName>
    <description>Stadium ID from Sports Data IO</description>
    <externalId>true</externalId>
    <label>Stadium Sports Data ID</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/assignStadiumsToGames.cls
global class assignStadiumsToGames {
   @InvocableMethod
   public static List<List<Game__c>> run(List<List<Game__c>> inputGames) {
       
      List<Stadium__c> allStadiums = [SELECT Id,Stadium_Sports_Data_ID__c FROM Stadium__c LIMIT 100];
      
      Map<String, Id> idMap = new Map<String, Id>();
      
      for (Stadium__c stadium : allStadiums) {
          idMap.put(String.valueOf(stadium.Stadium_Sports_Data_ID__c),stadium.Id);
      }
       
       
      for (List<Game__c> gameList : inputGames) {
          for (Game__c game : gameList) {
              game.Stadium__c = idMap.get(game.Stadium__c);
          }
      } 
      
     
      return inputGames;
   }
}