force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <description>An MLB game.</description>
    <label>Game</label>
    <nameField>
        <displayFormat>MLB-{00000}</displayFormat>
        <label>Game Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/fields/Away_Team__c.field-meta.xml
<CustomField>
    <fullName>Away_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Away Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Games (Away Team)</relationshipLabel>
    <relationshipName>Games_Away</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Games (Home Team)</relationshipLabel>
    <relationshipName>Games_Home</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>An MLB team.</description>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Abbreviation__c.field-meta.xml
<CustomField>
    <fullName>Abbreviation__c</fullName>
    <externalId>true</externalId>
    <label>Abbreviation</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/assignTeamstoGames.cls
global class assignTeamstoGames {
   @InvocableMethod
   public static List<List<Game__c>> run(List<List<Game__c>> inputGames) {
       
      List<Team__c> allTeams = [SELECT Id,Abbreviation__c FROM Team__c LIMIT 100];
      
      Map<String, Id> abbreviationMap = new Map<String, Id>();
      
      for (Team__c team : allTeams) {
          abbreviationMap.put(team.Abbreviation__c,team.Id);
      }
       
       
       
       
      for (List<Game__c> gameList : inputGames) {
          for (Game__c game : gameList) {
              game.Away_Team__c = abbreviationMap.get(game.Away_Team__c);
              game.Home_Team__c = abbreviationMap.get(game.Home_Team__c);
          }
      } 
      
      
     
      return inputGames;
   }
}